import { ManuscriptFragment } from '../types/fragment';

// List of transparent fragment image filenames (generated by segmentation model)
const fragmentFiles = [
  'OR15013_381A_L [BLL250]_fragment_1_conf0.98.png',
  'OR15013_381B_L [BLL250]_fragment_1_conf0.99.png',
  'OR15013_382A_L [BLL250]_fragment_1_conf0.97.png',
  'OR15013_382B_L [BLL250]_fragment_1_conf0.98.png',
  'OR15013_383A_L [BLL250]_fragment_1_conf0.99.png',
  'OR15013_383B_L [BLL250]_fragment_1_conf0.95.png',
  'OR15013_384A_L [BLL250]_fragment_1_conf0.96.png',
  'OR15013_384B_L [BLL250]_fragment_1_conf0.98.png',
  'OR15013_385A_L [BLL250]_fragment_1_conf0.97.png',
  'OR15013_385B_L [BLL250]_fragment_1_conf0.98.png',
  'OR15013_386A_L [BLL250]_fragment_1_conf0.97.png',
  'OR15013_386B_L [BLL250]_fragment_1_conf0.96.png',
  'OR15013_387A_L [BLL250]_fragment_1_conf0.96.png',
  'OR15013_387B_L [BLL250]_fragment_1_conf0.98.png',
  'OR15013_388A_L [BLL250]_fragment_1_conf0.84.png',
  'OR15013_388B_L [BLL250]_fragment_1_conf0.93.png',
  'OR15013_389A_L [BLL250]_fragment_1_conf0.94.png',
  'OR15013_389B_L [BLL250]_fragment_1_conf0.95.png',
  'OR15013_82A_L [BLL250]_fragment_1_conf0.92.png',
  'OR15013_82B_L [BLL250]_fragment_1_conf0.96.png',
];

// Sample metadata for demonstration (will be populated by ML models in production)
const sampleMetadata: { [key: number]: { lineCount?: number; script?: string; isEdgePiece?: boolean } } = {
  0: { lineCount: 4, script: 'Brahmi', isEdgePiece: true },
  1: { lineCount: 5, script: 'Brahmi', isEdgePiece: false },
  2: { lineCount: 3, script: 'Kharosthi', isEdgePiece: true },
  3: { lineCount: 6, script: 'Brahmi', isEdgePiece: false },
  4: { lineCount: 2, script: 'Kharosthi', isEdgePiece: true },
};

export const fragments: ManuscriptFragment[] = fragmentFiles.map((file, index) => ({
  id: `fragment-${index}`,
  name: file.replace(/_fragment_\d+_conf[\d.]+\.png$/, ''), // Remove fragment suffix and extension
  imagePath: `/images/transparent_fragments/${file}`,
  thumbnailPath: `/images/transparent_fragments/${file}`, // For POC, using same image as thumbnail
  metadata: sampleMetadata[index], // Optional metadata
}));

export const getFragmentById = (id: string): ManuscriptFragment | undefined => {
  return fragments.find(f => f.id === id);
};

/**
 * Sort fragments by search relevance
 * Priority: exact match → starts with query → contains query
 */
export function sortBySearchRelevance(
  fragments: ManuscriptFragment[],
  searchQuery: string
): ManuscriptFragment[] {
  const query = searchQuery.toLowerCase().trim();

  return [...fragments].sort((a, b) => {
    const aId = a.id.toLowerCase();
    const bId = b.id.toLowerCase();

    // Exact match priority
    const aExact = aId === query;
    const bExact = bId === query;
    if (aExact && !bExact) return -1;
    if (!aExact && bExact) return 1;

    // Starts with priority
    const aStarts = aId.startsWith(query);
    const bStarts = bId.startsWith(query);
    if (aStarts && !bStarts) return -1;
    if (!aStarts && bStarts) return 1;

    // Alphabetical fallback
    return aId.localeCompare(bId);
  });
}

/**
 * Calculate centered position on canvas
 */
export function calculateCenteredPosition(
  canvasWidth: number,
  canvasHeight: number,
  fragmentWidth: number,
  fragmentHeight: number
): { x: number; y: number } {
  return {
    x: (canvasWidth - fragmentWidth) / 2,
    y: (canvasHeight - fragmentHeight) / 2,
  };
}
